### ISSUE TITLE
I am trying to use v1.1.0 in my oneida-from-english but it isn't working

### ISSUE THREAD

**Issue by cutthroat78** [LibreLingo/course-ci#6]
Here is the log where it is not working
```
Run npx semantic-release
npm WARN exec The following package was not found and will be installed: semantic-release
[11:45:44 AM] [semantic-release] › ℹ  Running semantic-release version 19.0.2
[11:45:45 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[11:45:45 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[11:45:45 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[11:45:45 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[11:45:45 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[11:45:45 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[11:45:45 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[11:45:45 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[11:45:45 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[11:45:45 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[11:45:45 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[11:45:46 AM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[11:45:46 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[11:45:46 AM] [semantic-release] › ✖  Failed step "fail" of plugin "@semantic-release/github"
[11:45:46 AM] [semantic-release] › ✖  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository cutthroat78/Librelingo-Oneida-From-English.

[11:45:46 AM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).

This may occur if your repository does not have a release branch, such as master.

Your configuration for the problematic branches is [].

AggregateError: 
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/get-error.js:6:10)
        at /home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/branches/index.js:44:19
        at Array.reduce (<anonymous>)
        at module.exports (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/branches/index.js:34:46)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async run (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/index.js:65:22)
        at async module.exports (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/index.js:268:22)
        at async module.exports (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/cli.js:55:5)
    at module.exports (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/branches/index.js:66:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/index.js:65:22)
    at async module.exports (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/index.js:268:22)
    at async module.exports (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/cli.js:55:5)
Error: Process completed with exit code 1.
```

**Comment by cutthroat78** [comment]
I just copied the .github/workplace/main.yml to .github/workplace/main.yml of my repo and the action.yml to the root of my repo
Did I make a mistake or is there a problem with the github action?

**Comment by cutthroat78** [comment]
I have solved this issue by renaming my "main" branch to "master"
